name: Question
description: Ask a question and get help from the community
title: "[Q&A] "
labels: ["question", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! Please provide as much context as possible to help the community help you.
        
        **Before posting:**
        - [ ] I have searched existing discussions
        - [ ] I have checked the documentation
        - [ ] I have checked existing issues

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is your question?
      placeholder: "How do I connect to a MySQL database?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: What I'm trying to do
      description: Describe what you're trying to accomplish
      placeholder: "I want to connect my analytics agent to a MySQL database for reporting..."
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What I've tried
      description: What have you already tried? Include code examples, error messages, etc.
      placeholder: |
        I tried using the connection string format from the docs but got an error...
        
        Error: Connection failed
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: Windows 10
        - Python: 3.11.0
        - AI Agent Connector: 0.1.0
        - Database: MySQL 8.0
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, screenshots, logs, etc.
      placeholder: "Add any other context, screenshots, or logs here"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing discussions
          required: false
        - label: I have checked the documentation
          required: false
        - label: I have checked existing issues
          required: false

